apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/dconde-jx-test/environment-houndautumn-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: apps-dev-229310
    envOrganisation: dconde-jx-test
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: daveconde-jx-bot
    promotionEngine: Prow
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://davec-test-gitops32-lts-75b90efa-9b1e-4e87-95d9-1ee05e72c484
      classifier: default
    - bucketUrl: gs://davec-test-gitops32-lts-75b90efa-9b1e-4e87-95d9-1ee05e72c484
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
